---
title: "Copepod analysis"
author: "Sam Bashevkin"
date: "12/9/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages

```{r}
require(tidyverse)
require(zooper)
require(lubridate)
require(brms)
```

#Load data

```{r}
PF<-zoopComb%>%
  filter(Taxname=="Pseudodiaptomus forbesi")%>%
  left_join(zoopEnvComb%>%
              select(-Source),
            by="SampleID")%>%
  filter(Year>1995)%>% # Introduced in 1987, give them 8 years to get established
  mutate(Date_num=as.numeric(Date))%>%
  mutate(SalSurf_l = log(SalSurf),
         Julian_day = yday(Date))%>%
  mutate_at(vars(Date_num, SalSurf, SalSurf_l, Temperature, Latitude, Longitude), list(s=~(.-mean(., na.rm=T))/sd(., na.rm=T)))%>%
  drop_na(Date, SalSurf, Temperature, Latitude, Longitude, CPUE)
```

#Exploratory plots

Salinity
```{r}
ggplot(filter(PF, Lifestage=="Adult"), aes(x=log(SalSurf), y=log(CPUE+1)))+
  geom_point(alpha=0.2)+
  scale_y_continuous(expand = expand_scale(mult=c(0.01, 0.05)))+
  scale_x_continuous(expand = expand_scale(mult=c(0.01, 0.05)))+
  facet_wrap(~month(Date))+
  theme_bw()+
  theme(panel.grid=element_blank())
```

Quadratic


Temperature
```{r}
ggplot(filter(PF, Lifestage=="Adult"), aes(x=Temperature, y=log(CPUE+1)))+
  geom_point(alpha=0.2)+
  scale_y_continuous(expand = expand_scale(mult=c(0.01, 0.05)))+
  scale_x_continuous(expand = expand_scale(mult=c(0.01, 0.05)))+
  facet_wrap(~month(Date))+
  theme_bw()+
  theme(panel.grid=element_blank())
```

More in warmer temperatures, even controlling for month

Tide
```{r}
ggplot(filter(PF, Lifestage=="Adult"), aes(x=Tide, y=log(CPUE+1)))+
  geom_boxplot()+
  geom_violin()+
  scale_y_continuous(expand = expand_scale(mult=c(0.01, 0.05)))+
  #scale_x_continuous(expand = expand_scale(mult=c(0.01, 0.05)))+
  theme_bw()+
  theme(panel.grid=element_blank())
```

Not much here

Secchi
```{r}
ggplot(filter(PF, Lifestage=="Adult"), aes(x=Secchi, y=log(CPUE+1)))+
  geom_point(alpha=0.2)+
  scale_y_continuous(expand = expand_scale(mult=c(0.01, 0.05)))+
  scale_x_continuous(expand = expand_scale(mult=c(0.01, 0.05)))+
  facet_wrap(~month(Date))+
  theme_bw()+
  theme(panel.grid=element_blank())
```

Unclear

#Model

```{r}
iterations <- 5e3
warmup <- iterations/4

mbase<-brm(CPUE ~ 1, family=hurdle_gamma(),
       data=filter(PF, Lifestage=="Adult"),
       prior=prior(normal(0,10), class="Intercept"),
       chains=1, cores=1,
       iter = iterations, warmup = warmup)

mbaseST<-brm(CPUE ~ t2(Latitude_s, Longitude_s, Date_num_s, d=c(2,1)), family=hurdle_gamma(),
       data=filter(PF, Lifestage=="Adult"),
       prior=prior(normal(0,10), class="Intercept")+
         prior(normal(0,5), class="b"),
       chains=1, cores=1,
       iter = iterations, warmup = warmup)

mbaseST2<-brm(CPUE ~ t2(Latitude_s, Longitude_s, Date_num_s, d=c(2,1)) + t2(Julian_day, bs="cc"), family=hurdle_gamma(),
       data=filter(PF, Lifestage=="Adult"),
       prior=prior(normal(0,10), class="Intercept")+
         prior(normal(0,5), class="b"),
       chains=1, cores=1,
       iter = iterations, warmup = warmup, control=list(adapt_delta=0.85))

save.image("~/SDP/CopModels.RData")

m<-brm(CPUE ~ s(SalSurf_s) + s(Temperature_s) + t2(Latitude_s, Longitude_s, Date_num_s), family=hurdle_gamma(),
       data=filter(PF, Lifestage=="Adult"),
       prior=prior(normal(0,10), class="Intercept")+
         prior(normal(0,5), class="b"),
       chains=1, cores=1,
       iter = iterations, warmup = warmup, control=list(adapt_delta=0.9))

m2<-brm(CPUE ~ poly(SalSurf_l_s, 2) + s(Temperature_s) + t2(Latitude_s, Longitude_s, Date_num_s, d=c(2,1)), family=hurdle_gamma(),
       data=filter(PF, Lifestage=="Adult"),
       prior=prior(normal(0,10), class="Intercept")+
         prior(normal(0,5), class="b"),
       chains=1, cores=1,
       iter = iterations, warmup = warmup, control=list(adapt_delta=0.9))

m3<-brm(CPUE ~ poly(SalSurf_l_s, 2) + s(Temperature_s) + t2(Latitude_s, Longitude_s, Date_num_s, d=c(2,1)) + t2(Julian_day, bs="cc"), family=hurdle_gamma(),
       data=filter(PF, Lifestage=="Adult"),
       prior=prior(normal(0,10), class="Intercept")+
         prior(normal(0,5), class="b"),
       chains=1, cores=1,
       iter = iterations, warmup = warmup, control=list(adapt_delta=0.9))
```


posterior predictive checks
```{r}
prop_zero <- function(x) mean(x == 0)

pp_check(m2, type="stat", stat=prop_zero)
```
